version: "3.8"
services:
  postgresql:
    image: postgres:13-alpine
    container_name: reenv_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
